plugins {
    id 'java'
}

group = 'com.zbennoz'
version = '1.0.0'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.release = 21
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
    compileOnly 'com.mysql:mysql-connector-j:8.3.0'
}

jar {
    archiveBaseName.set('ZBenLootr')
    archiveVersion.set('')
}

tasks.withType(ProcessResources) {
    filteringCharset = 'UTF-8'
}
