tab:
  branding:
    enabled: true
logging:
  blocks:
    enabled: true
  containers:
    enabled: true
  debug: false
  maxRowsPerQuery: 10
inspector:
  maxEntries: 20
adminmode:
  enableFly: true
ranks:
  defaultRank: Spieler
