# ZBenClaims configuration
# Color codes with & are supported.

database:
  file: "claims.db"

cache:
  preloadAllClaims: true

claims:
  disabledWorlds: []
  requireChunkLoaded: true

flags:
  default:
    interact_protected: false

ranks:
  list:
    Admin:
      priority: 100
      limit: 500
      tabPrefix: "&c[Admin]&r "
      chatPrefix: "&c[Admin]&r "
      nametagPrefix: "&c[Admin]&r "
      cost: 0.0
    VIP:
      priority: 80
      limit: 150
      tabPrefix: "&6[VIP]&r "
      chatPrefix: "&6[VIP]&r "
      nametagPrefix: "&6[VIP]&r "
      cost: 0.0
    Stammspieler:
      priority: 60
      limit: 75
      tabPrefix: "&a[Stamm]&r "
      chatPrefix: "&a[Stamm]&r "
      nametagPrefix: "&a[Stamm]&r "
      cost: 0.0
    Spieler:
      priority: 40
      limit: 25
      tabPrefix: "&7[Spieler]&r "
      chatPrefix: "&7[Spieler]&r "
      nametagPrefix: "&7[Spieler]&r "
      cost: 0.0
    Beginner:
      priority: 20
      limit: 10
      tabPrefix: "&f[Beginner]&r "
      chatPrefix: "&f[Beginner]&r "
      nametagPrefix: "&f[Beginner]&r "
      cost: 0.0
  mode: "auto"

autosort:
  enabled: true
  player_inventory: true
  containers: true
  sort_hotbar: false
  requires_permission: false

tablist:
  enabled: true
  branding:
    enabled: true
    header: "&6Hostet by &aZBenNoz Gaming"
    footer: "&7Webseite: &bhttps://zbennoz.com"
