name: ZBenEnchants
version: ${version}
main: com.zbennoz.zbenenchants.core.ZBenEnchantsPlugin
author: zbennoz
api-version: '1.21'
softdepend: [ZBenClaims]
commands:
  zbenenchants:
    usage: /zbenenchants
    description: Verwalte ZBenEnchants
permissions:
  zbenenchants.givebook:
    description: Erlaubt das Geben von Enchant-Büchern
    default: op
  zbenenchants.reload:
    description: Erlaubt das Neuladen der Config
    default: op
