starting-coins: 1000
currency-name: "ZBenCoins"
gui:
  title: "&8&lZBenMarkt"
pay:
  min-amount: 1
limits:
  enable: true
  default-max-offers: 5
listing-fee:
  enabled: false
  flat: 0
  percent: 0
market:
  default-duration-hours: 24
  default-limit: 3
serverOffers:
  enabled: true
  dropItemIfInventoryFull: true
  defaultBuyAmounts: [1,16,64]
  defaultSellAmounts: [1,16,64]
jobs:
  default-expiry-hours: 48
  default-max-creator: 5
  default-max-assignee: 3
  history-limit: 10
