name: ZBenCoins
main: com.zbennoz.zbencoins.ZBenCoinsPlugin
version: 0.1.0
author: ZBenNoz
api-version: '1.21'
depend: []
commands:
  markt:
    description: Öffnet den ZBenMarkt.
    usage: /markt
    permission: zbencoins.market.use
  serveroffer:
    description: Verwalte Server-Angebote.
    usage: /serveroffer <create|delete|toggle|price|min|max> [...]
    permission: zbencoins.admin.serveroffers
  coins:
    description: Zeigt den Kontostand an.
    usage: /coins [spieler]
    permission: zbencoins.coins.use
  pay:
    description: Sende Coins an einen Spieler.
    usage: /pay <spieler> <betrag>
    permission: zbencoins.pay.use
  baltop:
    description: Zeigt die reichsten Spieler.
    usage: /baltop
    permission: zbencoins.baltop.use
permissions:
  zbencoins.market.use:
    description: Erlaube das Öffnen des Markt GUIs.
    default: true
  zbencoins.market.create:
    description: Erlaube das Erstellen eigener Spieler-Angebote.
    default: true
  zbencoins.market.buy:
    description: Erlaube das Kaufen von Spieler-Angeboten.
    default: true
  zbencoins.market.search:
    description: Erlaubt die Textsuche im Markt.
    default: true
  zbencoins.market.filter:
    description: Erlaubt Filter und Sortierung im Markt.
    default: true
  zbencoins.coins.use:
    description: Erlaube das Abfragen des eigenen Kontostands.
    default: true
  zbencoins.coins.others:
    description: Erlaube das Abfragen von fremden Kontoständen.
    default: op
  zbencoins.pay.use:
    description: Erlaube das Versenden von Coins.
    default: true
  zbencoins.baltop.use:
    description: Erlaube das Anzeigen der reichsten Spieler.
    default: true
  zbencoins.admin:
    description: Adminrechte für zukünftige Features.
    default: op
  zbencoins.jobs.create:
    description: Erlaube das Erstellen von Jobs.
    default: true
  zbencoins.jobs.accept:
    description: Erlaube das Annehmen von Jobs.
    default: true
  zbencoins.jobs.admin:
    description: Verwaltungsrechte für Jobs.
    default: op
  zbencoins.admin.serveroffers:
    description: Verwaltungsrechte für Server-Angebote.
    default: op
  zbencoins.serveroffers.use:
    description: Erlaube den Zugriff auf Server-Angebote.
    default: true
  zbencoins.serveroffers.bypasslimits:
    description: Umgeht Mengenbegrenzungen für Server-Angebote.
    default: op
