plugins {
    id 'java'
}

group = 'com.zbennoz'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT"
    implementation "org.xerial:sqlite-jdbc:3.46.1.0"
    compileOnly files("${rootDir}/../ZBenAdmintool/build/libs/ZBenAdmintool-1.0.0.jar")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(21)
}
