name: ZBenTimber
version: ${version}
main: com.zbennoz.zbentimber.ZBenTimberPlugin
author: zbennoz
api-version: '1.21'
commands:
  timber:
    description: "Schalte Timber-Optionen um"
    usage: "/timber leaves [on|off]"
permissions:
  zbentimber.tree:
    default: true
  zbentimber.ore:
    default: true
  zbentimber.stone:
    default: true
  zbentimber.admin:
    default: op
